from __future__ import annotations

from typing import Protocol

from app.models.audit import AuditRecord
from app.models.job import AuditJob


class AuditRepository(Protocol):
    def save_audit(self, audit: AuditRecord) -> AuditRecord: ...

    def get_audit(self, audit_id: str) -> AuditRecord | None: ...

    def list_audits(self) -> list[AuditRecord]: ...

    def delete_audit(self, audit_id: str) -> None: ...

    def next_version(self, ticket_id: str) -> int: ...

    def save_job(self, job: AuditJob) -> AuditJob: ...

    def get_job(self, job_id: str) -> AuditJob | None: ...

    def list_jobs(self) -> list[AuditJob]: ...

    def delete_job(self, job_id: str) -> None: ...
